"""add draft order and timer fields

Revision ID: 1a8dd5b75455
Revises: bbfeb879b207
Create Date: 2025-07-10 21:04:22.494389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1a8dd5b75455'
down_revision: Union[str, None] = 'bbfeb879b207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draftsession', sa.Column('draft_order', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('draftsession', sa.Column('current_pick_index', sa.Integer(), nullable=False))
    op.add_column('draftsession', sa.Column('pick_deadline', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draftsession', 'pick_deadline')
    op.drop_column('draftsession', 'current_pick_index')
    op.drop_column('draftsession', 'draft_order')
    # ### end Alembic commands ###
