"""add live score, map_round, player_stat tables

Revision ID: 1cec025e6f03
Revises: cebc5bac8311
Create Date: 2025-05-22 13:21:53.791679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1cec025e6f03'
down_revision: Union[str, None] = 'cebc5bac8311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livescore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team1_score', sa.Integer(), nullable=False),
    sa.Column('team2_score', sa.Integer(), nullable=False),
    sa.Column('current_map', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mapround',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('map_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team1_rounds', sa.Integer(), nullable=False),
    sa.Column('team2_rounds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playerstat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('map_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('player_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('match', 'vlr_match_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_match_vlr_match_id', table_name='match')
    op.drop_index('ix_match_match_page', table_name='match')
    op.create_index(op.f('ix_match_match_page'), 'match', ['match_page'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_match_page'), table_name='match')
    op.create_index('ix_match_match_page', 'match', ['match_page'], unique=False)
    op.create_index('ix_match_vlr_match_id', 'match', ['vlr_match_id'], unique=True)
    op.alter_column('match', 'vlr_match_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('playerstat')
    op.drop_table('mapround')
    op.drop_table('livescore')
    # ### end Alembic commands ###
