"""Add cascade delete to LeagueMember.user_id foreign key

Revision ID: 355ae68a771a
Revises: 1a8dd5b75455
Create Date: 2025-07-14 22:28:29.269945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '355ae68a771a'
down_revision: Union[str, None] = '1a8dd5b75455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('leaguemember_user_id_fkey'), 'leaguemember', type_='foreignkey')
    op.create_foreign_key(None, 'leaguemember', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leaguemember', type_='foreignkey')
    op.create_foreign_key(op.f('leaguemember_user_id_fkey'), 'leaguemember', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
