"""Add cascade delete to Team.user_id foreign key

Revision ID: 41b342e7c65f
Revises: 355ae68a771a
Create Date: 2025-07-14 22:31:02.189458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '41b342e7c65f'
down_revision: Union[str, None] = '355ae68a771a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('team_user_id_fkey'), 'team', type_='foreignkey')
    op.create_foreign_key(None, 'team', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.create_foreign_key(op.f('team_user_id_fkey'), 'team', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
