"""add_admin_table

Revision ID: 534bbd25e1e0
Revises: ed0bef490d1f
Create Date: 2025-08-16 22:23:17.694675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '534bbd25e1e0'
down_revision: Union[str, None] = 'ed0bef490d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('can_manage_players', sa.Boolean(), nullable=False),
    sa.Column('can_manage_users', sa.Boolean(), nullable=False),
    sa.Column('can_manage_leagues', sa.Boolean(), nullable=False),
    sa.Column('can_manage_matches', sa.Boolean(), nullable=False),
    sa.Column('can_view_analytics', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_username'), 'admin', ['username'], unique=True)
    op.alter_column('agentprediction', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('agentprediction', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_agentprediction_team_player_created'), table_name='agentprediction')
    op.drop_constraint(op.f('agentprediction_team_id_fkey'), 'agentprediction', type_='foreignkey')
    op.drop_constraint(op.f('agentprediction_player_name_fkey'), 'agentprediction', type_='foreignkey')
    op.create_foreign_key(None, 'agentprediction', 'team', ['team_id'], ['id'])
    op.create_foreign_key(None, 'agentprediction', 'players', ['player_name'], ['player_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agentprediction', type_='foreignkey')
    op.drop_constraint(None, 'agentprediction', type_='foreignkey')
    op.create_foreign_key(op.f('agentprediction_player_name_fkey'), 'agentprediction', 'players', ['player_name'], ['player_name'], ondelete='CASCADE')
    op.create_foreign_key(op.f('agentprediction_team_id_fkey'), 'agentprediction', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_agentprediction_team_player_created'), 'agentprediction', ['team_id', 'player_name', 'created_at'], unique=False)
    op.alter_column('agentprediction', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('agentprediction', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_admin_username'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
