"""create_match_table

Revision ID: 6d8b865fb190
Revises: 
Create Date: 2025-05-17 08:02:30.572495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Import for SQLModel types if needed, though not directly for op commands


# revision identifiers, used by Alembic.
revision: str = '6d8b865fb190'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('team1', sa.String(), nullable=True),
    sa.Column('team2', sa.String(), nullable=True),
    sa.Column('match_series', sa.String(), nullable=True),
    sa.Column('match_event', sa.String(), nullable=True),
    sa.Column('unix_timestamp', sa.Integer(), nullable=True),
    sa.Column('match_page', sa.String(), nullable=False),
    # vlr_match_id is not included here, it will be added by the next migration cebc5bac8311
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_id'), 'match', ['id'], unique=False)
    op.create_index(op.f('ix_match_match_page'), 'match', ['match_page'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_match_page'), table_name='match')
    op.drop_index(op.f('ix_match_id'), table_name='match')
    op.drop_table('match')
    # ### end Alembic commands ###
