"""add score field to player_stat table

Revision ID: 71c731951d46
Revises: aac378e32527
Create Date: 2025-06-18 19:38:59.498686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71c731951d46'
down_revision: Union[str, None] = 'aac378e32527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playerstat', sa.Column('score', sa.Float(), nullable=True))
    op.drop_column('playerstat', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playerstat', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('playerstat', 'score')
    # ### end Alembic commands ###
