"""add_use_best_2_of_3_to_league_settings

Revision ID: 94132139b3a0
Revises: 41b342e7c65f
Create Date: 2025-07-31 16:30:04.529127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '94132139b3a0'
down_revision: Union[str, None] = '41b342e7c65f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaguesettings', sa.Column('use_best_2_of_3', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leaguesettings', 'use_best_2_of_3')
    # ### end Alembic commands ###
