"""add_password_and_is_active_to_user

Revision ID: 9878a26aa20b
Revises: 94132139b3a0
Create Date: 2025-08-07 05:32:11.550344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9878a26aa20b'
down_revision: Union[str, None] = '94132139b3a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add join_pin to league table and index if not exists
    try:
        with op.batch_alter_table('league', schema=None) as batch_op:
            batch_op.add_column(sa.Column('join_pin', sa.String(length=6), nullable=True))
            batch_op.create_index('ix_league_join_pin', ['join_pin'], unique=False)
    except Exception:
        # In case it already exists
        pass
    # Add columns as nullable first
    op.add_column('user', sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    
    # Set default values for existing users
    op.execute("UPDATE \"user\" SET hashed_password = 'temp_password_change_me' WHERE hashed_password IS NULL")
    op.execute("UPDATE \"user\" SET is_active = true WHERE is_active IS NULL")
    
    # Now make them non-nullable
    op.alter_column('user', 'hashed_password', nullable=False)
    op.alter_column('user', 'is_active', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('league', schema=None) as batch_op:
            batch_op.drop_index('ix_league_join_pin')
            batch_op.drop_column('join_pin')
    except Exception:
        pass
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###
