"""add detailed map and player stats

Revision ID: aac378e32527
Revises: 1cec025e6f03
Create Date: 2025-05-27 08:49:01.644427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aac378e32527'
down_revision: Union[str, None] = '1cec025e6f03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapround', sa.Column('team1_attack_rounds', sa.Integer(), nullable=True))
    op.add_column('mapround', sa.Column('team1_defense_rounds', sa.Integer(), nullable=True))
    op.add_column('mapround', sa.Column('team2_attack_rounds', sa.Integer(), nullable=True))
    op.add_column('mapround', sa.Column('team2_defense_rounds', sa.Integer(), nullable=True))
    op.add_column('playerstat', sa.Column('agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('playerstat', sa.Column('deaths', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playerstat', 'deaths')
    op.drop_column('playerstat', 'agent')
    op.drop_column('mapround', 'team2_defense_rounds')
    op.drop_column('mapround', 'team2_attack_rounds')
    op.drop_column('mapround', 'team1_defense_rounds')
    op.drop_column('mapround', 'team1_attack_rounds')
    # ### end Alembic commands ###
