"""add_vlr_match_id_to_match_table

Revision ID: cebc5bac8311
Revises: 6d8b865fb190
Create Date: 2025-05-19 13:40:06.388174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Added for SQLModel specific types if needed, but not directly used in ops


# revision identifiers, used by Alembic.
revision: str = 'cebc5bac8311'
down_revision: Union[str, None] = '6d8b865fb190'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('vlr_match_id', sa.String(), nullable=True))
    
    # Backfill vlr_match_id from match_page
    # Assuming match_page format is a full URL like 'https://www.vlr.gg/MATCH_ID/MATCH_SLUG'
    # This SQL uses a regular expression to extract MATCH_ID (the digits after 'vlr.gg/').
    # Ensure that existing vlr_match_id are not overwritten if script is re-run, though migrations should run once.
    op.execute(
        "UPDATE match SET vlr_match_id = substring(match_page from 'vlr\\.gg/(\\d+)/') "
        "WHERE match_page ~ 'vlr\\.gg/\\d+/' AND vlr_match_id IS NULL"
    )

    # Make vlr_match_id non-nullable after backfilling
    op.alter_column('match', 'vlr_match_id', existing_type=sa.String(), nullable=False)
    
    op.create_index(op.f('ix_match_vlr_match_id'), 'match', ['vlr_match_id'], unique=True)
    
    # Drop the old unique index on match_page if it exists
    # The name 'ix_match_match_page' is assumed based on typical naming conventions for 'index=True, unique=True'
    # If SQLModel created it with a different name, this might need adjustment.
    # First, check if the index exists to avoid errors if it was already removed or named differently.
    # This is a bit more complex to do robustly in Alembic without knowing the exact DB state or original constraint name.
    # For now, we'll assume op.f() gives the correct name for an index created by unique=True, index=True.
    try:
        op.drop_index(op.f('ix_match_match_page'), table_name='match')
    except Exception as e:
        print(f"Could not drop unique index ix_match_match_page (it might not exist or have a different name): {e}")

    # Create a new non-unique index on match_page
    op.create_index(op.f('ix_match_match_page'), 'match', ['match_page'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_match_page'), table_name='match')
    
    # Recreate the unique index on match_page that was (presumably) there before
    # This assumes it was named 'ix_match_match_page' and was unique.
    op.create_index(op.f('ix_match_match_page'), 'match', ['match_page'], unique=True)
    
    op.drop_index(op.f('ix_match_vlr_match_id'), table_name='match')
    op.drop_column('match', 'vlr_match_id')
    # ### end Alembic commands ###
