"""remove_unique_constraint_from_league_name

Revision ID: e98d52dd1f39
Revises: 1bfb3fa8b2b7
Create Date: 2026-01-07 19:42:53.072957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e98d52dd1f39'
down_revision: Union[str, None] = '1bfb3fa8b2b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('league_name_key'), 'league', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('league_name_key'), 'league', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
